In [1]:
import numpy as np
import scipy as sp
from env.shortestpath import ShortestPathEnv
import networkx as nx

In [2]:
node_number = 5

A = sp.sparse.random(node_number, node_number, density=0.5, format='csr')
A.data[:] = 1
A = A.todense()
A = np.ma.array(A, mask=np.eye(node_number)).filled(fill_value=0).astype(int)
print("sparsity = %.2f" % (1 - np.sum(A)/A.size))
G = nx.from_numpy_array(A, create_using=nx.DiGraph)


sparsity = 0.60


In [7]:
env = ShortestPathEnv(G, 0, 4)

In [8]:
print(env.adj_mat)
print(env.adj_indices)

[[0 1 1 1 0]
 [1 0 1 0 0]
 [0 0 0 1 1]
 [1 1 0 0 0]
 [0 0 1 0 0]]
[array([1, 2, 3]), array([0, 2]), array([3, 4]), array([0, 1]), array([2])]


In [9]:
p, r, d = env.step(4)
p, r, d = env.step(3)
p

3

In [13]:
p, r, d = env.step(1)
p,r,d

(1, -1, False)

In [14]:
p, r, d = env.step(2)
p, r, d

(2, -1, False)

In [15]:
p, r, d = env.step(4)
p, r, d

(4, 0, True)